// Generated by tools/schema/generate-job-event-types.mjs. Do not edit.
/** State names from the job state machine. */
export type JobStatus = "Queued" | "Running" | "Completed" | "Failed" | "Retrying" | "Cancelled";
export const JOB_PROGRESS_STAGES = [
  "staging",
  "validating",
  "probing",
  "decoding",
  "proxy",
  "asr",
  "mix",
  "poster",
  "sprite",
  "uploading",
  "finalizing",
] as const;
export type JobProgressStage = (typeof JOB_PROGRESS_STAGES)[number];
interface JobEventBase {
  readonly schemaVersion: 1;
  readonly eventId: string;
  readonly jobId: string;
  readonly jobType: string;
  readonly projectId: string;
  readonly sequence: number;
  readonly attempt: number;
  readonly occurredAt: string;
  readonly correlationId?: string;
}
export type JobEvent = JobEventBase &
  (
    | {
        readonly kind: "progress";
        readonly percentage: number;
        readonly stage: JobProgressStage;
      }
    | {
        readonly kind: "state";
        readonly status: JobStatus;
        readonly reason?: "processing_failed" | "cancelled";
      }
  );
